# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pedro Pagani
title: Full-time dev at Oath Tentacles
email: pedro.paulo.pagani@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Discord
  icon: fas fa-globe
  url: https://discord.com/invite/3zV5Vvjw8m
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pedro and i am a Fulltime developer at Oath tentacles, i have experience making software for minecraft servers. I have already worked at many servers gaining teamwork and leadership skills.

  I am most skilled in: <mark>Multi-Threading</mark> and <mark>Minigames Frameworks</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Resume Projects
        link: github.com/PedroMPagani
        # link_text: Project Website
        additional_links:
          - title: Resume Projects
            icon: fab fa-github
            url: github.com/PedroMPagani/Resume
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          When coding you are basically dreaming, the fact that you can write words and turn ideas into reality inspiree every kid, you don't even need to teach them.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>Spigot/Bukkit</mark> and it went well. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Oath Tentacles
        # link_text: boringcompany.com
        sub_title: Java Dev
        quote: >
          Turning dreams into reality, it is something that we are capable of.
        description: | # this will include new lines to allow paragraphs
            Always looking forward to provide software with high quality and performance to the servers around the Minecraft community.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
